{{- if .Values.pdb.create -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "twingate-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "twingate-operator.labels" . | nindent 4 }}
spec:
{{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
{{- end }}
{{- if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
{{- end }}
  selector:
    matchLabels:
      {{- include "twingate-operator.selectorLabels" . | nindent 6 }}
{{- end }}
