apiVersion: twingate.com/v1beta
kind: TwingateConnector
metadata:
  name: my-connector
spec:
  # Can use `image` OR `imagePolicy`
  # - `image` - is manual hardcoded image - you can point it to any repository and any tag you want and its fixed
  # - `imagePolicy` - gets a schedule and a versionSpecifier and auto updates
  image:
    repository: twingate/connector
    tag: latest
  imagePolicy:
    provider: "dockerhub" # dockerhub | google
    schedule: "* * * * *"
    repository: twingate/connector
    version: "^1.0.0"

  containerExtra:
    resources:
      requests:
        cpu: 314m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 128Mi
  podExtra: {}
