apiVersion: v1
kind: Service
metadata:
  name: my-service
  annotations:
    twingate.com/expose: "true"
    twingate.com/expose-alias: "myapp.internal"
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
