name: Vulnerability-Monitor

on:
  schedule:
    - cron: "0 17 * * 1"  # 9am Monday PST

jobs:
  docker-image-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Scan docker vulnerabilities
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s --
          set +e
          docker scout cves twingate/kubernetes-operator:dev -e --only-fixed --only-severity medium,high,critical --output scout-result.txt
          if [ $? -eq 2 ]
          then
            echo "Found vulnerabilities!  Posting to Slack..."
            CURL_DATA='{"text": "Kubernetes Operator - new fixable vulnerability found:\n '$(cat scout-result.txt)'\n"}';
            curl -X POST -H 'Content-type: application/json' --data "$CURL_DATA" $SLACK_WEBHOOK_URL
          fi
