name: Vulnerability-Monitor

on:
  schedule:
    - cron: "0 16 * * *"

jobs:
  docker-image-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
          sudo apt-get update
          sudo apt-get install jq
          curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s --
          docker scout cves twingate/kubernetes-operator:dev --only-fixed --format sarif --output kubernetes-operator.sarif.json
          if [ `cat kubernetes-operator.sarif.json | jq -r '.runs[0].results | length'` -gt 0 ];
          then docker scout cves twingate/kubernetes-operator:dev --only-fixed --output kubernetes-operator.txt;
          export IFS=","
          SLACK_MENTION_STRING="(cc "
          for user in $DOCKER_VULNERABILITY_SLACK_MENTIONS; do
            echo "<@$user>"
            SLACK_MENTION_STRING+="<@$user>"
          done
            SLACK_MENTION_STRING+=")"
            echo $SLACK_MENTION_STRING
          CURL_DATA='{"text": "Kubernetes Operator new fixable vulnerability found:\n '$(cat kubernetes-operator.txt)'\n '$SLACK_MENTION_STRING'"}';
          curl -X POST -H 'Content-type: application/json' --data "$CURL_DATA" $SLACK_WEBHOOK_URL
          fi
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          DOCKER_VULNERABILITY_SLACK_MENTIONS: ${{ secrets.DOCKER_VULNERABILITY_SLACK_MENTIONS }}
        name: Run on VM
