name: Vulnerability-Monitor

on:
  push:
    branches:
      - 'cb/docker-vulnerability-monitor'

jobs:
  docker-image-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Scout
        id: docker-scout
        uses: docker/scout-action@v1
        with:
          command: cves
          image: twingate/kubernetes-operator:dev
          only-fixed: true
          sarif-file: kubernetes-operator.sarif.json
      - run: |
          sudo apt-get update
          sudo apt-get install jq
          cat kubernetes-operator.sarif.json
          echo ${{ steps.docker-scout.outputs }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          DOCKER_VULNERABILITY_SLACK_MENTIONS: ${{ secrets.DOCKER_VULNERABILITY_SLACK_MENTIONS }}
        name: Run on VM
